export const referalBadgeName = "Growth Ambassador"
export const streakBadge = "Week Warrior"
export const leaderboardBadgeTop10 = "Elite Climber"
export const leaderboardBadgeTop1 = "Supreme Champion"
export const beamsTodayBadge10 = "Momentum Master"
export const beamsTodayBadge50 = "Perpetual Performer"
